services:
  collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    # command: --logging.level.zipkin2=DEBUG

  grafana:
    image: grafana/grafana
    user: 1000:1000
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    #   - GF_SECURITY_ADMIN_USER=admin
    #   - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      -  canvas-management-grafana:/var/lib/grafana
      - ./grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/main.yaml
      # - ./grafana-dashboard.json:/var/lib/grafana/dashboards/dash.json

  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  canvas-management-grafana:
