services:
  canvas_manager:
    image: alexmickelson/canvas_management:2.7
    user: "1000:1000"
    container_name: canvas-manager-2
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - storageDirectory=/app/storage
      - TZ=America/Denver
      - NEXT_PUBLIC_ENABLE_FILE_SYNC=true
      - REDIS_URL=redis://redis:6379
      # - FILE_POLLING=true
    volumes:
      # - ~/projects/faculty/3840_Telemetry/2024Spring_alex/modules:/app/storage/spring_2024_telemetry

      # - ~/projects/faculty/1400/2025_spring_alex/modules:/app/storage/1400
      # - ~/projects/faculty/1405/2025_spring_alex:/app/storage/1405
      # - ~/projects/faculty/3840_Telemetry/2025_spring_alex/modules:/app/storage/telemetry
      # - ~/projects/faculty/4620_Distributed/2025Spring/modules:/app/storage/distributed
      # - ~/projects/faculty/4620_Distributed/2024Spring/modules:/app/storage/distributed_old


      - ~/projects/faculty/1810/2025-spring-alex/in-person:/app/storage/intro_to_web_old
      - ~/projects/faculty/1810/2025-fall-alex/modules:/app/storage/intro_to_web

      - ~/projects/faculty/4850_AdvancedFE/2025-fall-alex/modules:/app/storage/advanced_frontend
      - ~/projects/faculty/4850_AdvancedFE/2024-fall-alex/modules:/app/storage/advanced_frontend_old

      - ~/projects/faculty/1430/2024-fall-alex/modules:/app/storage/ux_old
      - ~/projects/faculty/1430/2025-fall-alex/modules:/app/storage/ux

      - ~/projects/faculty/1420/2024-fall/Modules:/app/storage/1420_old
      - ~/projects/faculty/1420/2025-fall-alex/modules:/app/storage/1420
      
      - ~/projects/faculty/1425/2024-fall/Modules:/app/storage/1425_old
      - ~/projects/faculty/1425/2025-fall-alex/modules:/app/storage/1425

      - ~/projects/facultyFiles:/app/public/images/facultyFiles


  redis:
    image: redis
    container_name: redis
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
      
  # https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/
  # https://github.com/jonas-merkle/container-cloudflare-tunnel
  # cloudflare-tunnel:
  #   image: cloudflare/cloudflared
  #   container_name: cloudflare-tunnel
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   command: tunnel run
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
  #   healthcheck:
  #     test: [ "CMD", "cloudflared", "--version" ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 10s
  # https://ngrok.com/docs/using-ngrok-with/docker/
