services:
  canvas_manager:
    image: alexmickelson/canvas_management:3
    user: "1000:1000"
    container_name: canvas-manager
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - storageDirectory=/app/storage
      - TZ=America/Denver
      - NEXT_PUBLIC_ENABLE_FILE_SYNC=true
      - REDIS_URL=redis://redis:6379
      # - FILE_POLLING=true
    volumes:
      - ./globalSettings.yml:/app/globalSettings.yml
      - ~/projects/faculty:/app/storage
      - ~/projects/facultyFiles:/app/public/images/facultyFiles


#   redis:
#     image: redis
#     container_name: redis
#     volumes:
#       - redis-data:/data
#     restart: unless-stopped

# volumes:
#   redis-data:
      
  # https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/
  # https://github.com/jonas-merkle/container-cloudflare-tunnel
  # cloudflare-tunnel:
  #   image: cloudflare/cloudflared
  #   container_name: cloudflare-tunnel
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   command: tunnel run
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
  #   healthcheck:
  #     test: [ "CMD", "cloudflared", "--version" ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 10s
  # https://ngrok.com/docs/using-ngrok-with/docker/
