services:
  canvas_manager:
    image: alexmickelson/canvas_management:1.0
    user: "1000:1000"
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - storageDirectory=/app/storage
    volumes:
      - ./storage:/app/storage