services:
  canvas_manager:
    image: alexmickelson/canvas_management:1
    user: "1000:1000"
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - storageDirectory=/app/storage
      - TZ=America/Denver
    volumes:
      # - ./storage:/app/storage
      # - ~/projects/faculty/1410/2023-fall-alex/modules:/app/storage/1410
      - ~/projects/faculty/1810/2024-spring-alex/modules:/app/storage/web_intro
      - ~/projects/faculty/1400/2024_spring_alex/modules:/app/storage/1400
      - ~/projects/faculty/1405/2024_spring_alex/modules:/app/storage/1405
      - ~/projects/faculty/4620_Distributed/2024Spring/modules:/app/storage/distributed
      - ~/projects/faculty/3840_Telemetry/2024Spring_alex/modules:/app/storage/telemetry_and_operations

  collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./ops/otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to.
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Point the zipkin at the storage backend
      # - MYSQL_HOST=mysql
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    # Uncomment to enable debug logging
    # command: --logging.level.zipkin2=DEBUG
