services:
  canvas_manager:
    image: alexmickelson/canvas_management:2.4
    user: "1000:1000"
    container_name: canvas-manager-2
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - storageDirectory=/app/storage
      - TZ=America/Denver
      # - FILE_POLLING=true
    volumes:
      - ~/projects/faculty/1430/2024-fall-alex/modules:/app/storage/UX
      - ~/projects/faculty/4850_AdvancedFE/2024-fall-alex/modules:/app/storage/advanced_frontend

      - ~/projects/faculty/1810/2024-spring-alex/modules_online:/app/storage/intro_to_web_online_old
      - ~/projects/faculty/1810/2024-fall-alex/modules:/app/storage/intro_to_web_old
      - ~/projects/faculty/1810/2025-spring-alex/in-person:/app/storage/intro_to_web
      - ~/projects/faculty/1810/2025-spring-alex/online:/app/storage/intro_to_web_online

      - ~/projects/faculty/3840_Telemetry/2024Spring_alex/modules:/app/storage/spring_2024_telemetry
      - ~/projects/faculty/3840_Telemetry/2025_spring_alex/modules:/app/storage/spring_2025_telemetry
      - ~/projects/faculty/4620_Distributed/2025Spring/modules:/app/storage/distributed

  # https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/
  # https://github.com/jonas-merkle/container-cloudflare-tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflare-tunnel
    restart: unless-stopped
    env_file:
      - .env
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    healthcheck:
      test: ["CMD", "cloudflared", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s


  # https://ngrok.com/docs/using-ngrok-with/docker/
