services:
  canvas_manager:
    image: alexmickelson/canvas_management:2.6
    user: "1000:1000"
    container_name: canvas-manager-2
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - storageDirectory=/app/storage
      - TZ=America/Denver
      - NEXT_PUBLIC_ENABLE_FILE_SYNC=true
      # - FILE_POLLING=true
    volumes:
      - ~/projects/faculty/3840_Telemetry/2024Spring_alex/modules:/app/storage/spring_2024_telemetry

      - ~/projects/faculty/1400/2025_spring_alex/modules:/app/storage/1400
      - ~/projects/faculty/1405/2025_spring_alex:/app/storage/1405
      - ~/projects/faculty/3840_Telemetry/2025_spring_alex/modules:/app/storage/telemetry
      - ~/projects/faculty/4620_Distributed/2025Spring/modules:/app/storage/distributed
      - ~/projects/faculty/4620_Distributed/2024Spring/modules:/app/storage/distributed_old
      - ~/projects/faculty/1810/2025-spring-alex/in-person:/app/storage/intro_to_web
      - ~/projects/faculty/1810/2025-spring-alex/online:/app/storage/intro_to_web_online

      - ~/projects/facultyFiles:/app/public/images/facultyFiles
      
  # https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/
  # https://github.com/jonas-merkle/container-cloudflare-tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflare-tunnel
    restart: unless-stopped
    env_file:
      - .env
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    healthcheck:
      test: [ "CMD", "cloudflared", "--version" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  # https://ngrok.com/docs/using-ngrok-with/docker/
