
GET https://snow.instructure.com/api/v1/courses/1013058/quizzes
Authorization: Bearer {{$dotenv CANVAS_TOKEN}}

###
GET https://snow.instructure.com/api/v1/courses/926068/quizzes/3489332/questions
Authorization: Bearer {{$dotenv CANVAS_TOKEN}}

###


POST https://snow.instructure.com/api/v1/courses/926068/quizzes/3489331/reorder
Authorization: Bearer {{$dotenv CANVAS_TOKEN}}
Content-Type: application/json

{
  "order":[
    {"type":"question","id":"60973974"},
    {"type":"question","id":"60973977"},
    {"type":"question","id":"60973976"},
    {"type":"question","id":"60973975"},
    {"type":"question","id":"60973978"},
    {"type":"question","id":"60973979"},
    {"type":"question","id":"60973980"}
  ]
}


###
GET https://snow.instructure.com/api/v1/courses/958185/assignments
Authorization: Bearer {{$dotenv CANVAS_TOKEN}}

###
POST https://snow.instructure.com/api/v1/courses/958185/quizzes/3358912/questions
Authorization: Bearer {{$dotenv CANVAS_TOKEN}}
Content-Type: application/json

{
  "question":{
    "question_text": "dummy question via the api",
    "question_type": "multiple_answers_question",
    "points_possible": 3,
    "answers": [
      {
        "answer_text": "color",
        "answer_weight": 0
      },
      {
        "answer_text": "affordances",
        "answer_weight": 100
      },
      {
        "answer_text": "structure",
        "answer_weight": 0
      },
      {
        "answer_text": "constraints",
        "answer_weight": 100
      },
      {
        "answer_text": "mappings",
        "answer_weight": 100
      },
      {
        "answer_text": "placement",
        "answer_weight": 0
      }
    ]
  }
}
###
POST https://snow.instructure.com/api/v1/courses/958185/quizzes/3358912/questions
Authorization: Bearer {{$dotenv CANVAS_TOKEN}}
Content-Type: application/json

{
  "question": {
    "question_text": "dummy matching via the api",
    "question_type": "matching_question",
    "points_possible": 5,
    "answers": [
      {
        "correct": true,
        "answer_match_left": "statement",
        "answer_match_right": "a single command to be executed"
      },
      {
        "correct": true,
        "answer_match_left": "identifier",
        "answer_match_right": "name of a variable"
      },
      {
        "correct": true,
        "answer_match_left": "keyword",
        "answer_match_right": "reserved word that has special meaning in a program (e.g. class, void, static, etc.)"
      },
      {
        "correct": true,
        "answer_match_left": "source file",
        "answer_match_right": "the .cs text file containing your source code"
      }
    ]
  }
}
