services:
  canvas_manager:
    image: alexmickelson/canvas_management:2
    user: "1000:1000"
    container_name: canvas-manager-2
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - storageDirectory=/app/storage
      - TZ=America/Denver
    volumes:
      - ~/projects/faculty/1430/2024-fall-alex/modules:/app/storage/UX
      - ~/projects/faculty/4850_AdvancedFE/2024-fall-alex/modules:/app/storage/advanced_frontend
      - ~/projects/faculty/1810/2024-fall-alex/modules:/app/storage/intro_to_web
      # - ~/projects/faculty/1420/2024-fall/Modules:/app/storage/1420
      # - ~/projects/faculty/1425/2024-fall/Modules:/app/storage/1425