receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  # otlp:
  #   endpoint: otelcol:4317
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
    # metrics:
    #   receivers: []
    #   processors: [batch]
    #   exporters: []
    # logs:
    #   receivers: []
    #   processors: [batch]
    #   exporters: []
